Repository PrestaShop/distribution-api, pull requests merged in 2025-04, with the labels that each got.

#44 [FEAT] add release notes to prestashop version
  resources/json/releaseNotes.json
  src/Model/PrestaShop.php
  src/Util/PrestaShopUtils.php
  src/Util/ReleaseNoteUtils.php
  tests/Util/ReleaseNoteUtilsTest.php
  tests/ressources/json/prestashop.json
  tests/ressources/json/prestashop/beta.json
  tests/ressources/json/prestashop/rc.json
  tests/ressources/json/prestashop/stable.json
Labels: enhancement

#42 Add distribution for prestashop release
  src/Model/PrestaShop.php
  tests/Model/PrestaShopTest.php
  tests/ressources/json/prestashop.json
  tests/ressources/json/prestashop/beta.json
  tests/ressources/json/prestashop/rc.json
  tests/ressources/json/prestashop/stable.json
Labels: enhancement, integration-deployment

#45 [FEAT] change PrestaShop minimum version to include all version from 1.7
  config/parameters.yaml
  resources/json/prestashop17PhpCompat.json
  src/Util/PrestaShopUtils.php
  src/Util/VersionUtils.php
  tests/Command/GenerateJsonCommandTest.php
  tests/Util/VersionUtilsTest.php
  tests/ressources/json/prestashop.json
Labels: enhancement

#48 [FEAT] update workflows with latest version of actions
  .github/workflows/ci-cd-integration.yml
  .github/workflows/ci-cd-preproduction.yml
  .github/workflows/ci-cd-production.yml
Labels: enhancement, integration-deployment

#51 [FIX] Switch to Symfony HttpClient for HTTP requests
  composer.json
  composer.lock
  config/services.yaml
  src/Util/ModuleUtils.php
  src/Util/PrestaShopUtils.php
  tests/Command/GenerateJsonCommandTest.php
  tests/Command/UpdateModuleConfigFilesCommandTest.php
  tests/Util/ModuleUtilsTest.php
  tests/Util/PrestaShopUtilsTest.php
Labels: bug, integration-deployment
